# Rxyhn - Kitty Terminal Theme (from NvChad Base46 rxyhn)

background #061115
foreground #D9D7D6

cursor #78B892
cursor_text_color #061115

selection_background #313c40
selection_foreground #D9D7D6

active_tab_background #131e22
active_tab_foreground #D9D7D6
inactive_tab_background #061115
inactive_tab_foreground #8a9799

color0 #000a0e
color1 #DF5B61
color2 #78B892
color3 #ecd28b
color4 #6791C9
color5 #C488EC
color6 #7ACFE4
color7 #D9D7D6

color8 #4f5a5e
color9 #EE6A70
color10 #8CD7AA
color11 #f6dc95
color12 #79AAEB
color13 #BC83E3
color14 #67AFC1
color15 #EDEBEA

url_color #7ACFE4

mark1_foreground #061115
mark1_background #78B892
mark2_foreground #061115
mark2_background #6791C9
mark3_foreground #061115
mark3_background #C488EC
