# Osaka Jade - Kitty Terminal Theme

# Background
background #111c18

# Foreground
foreground #C1C497

# Cursor
cursor #C1C497
cursor_text_color #111c18

# Selection
selection_background #32473B
selection_foreground #C1C497

# Tab bar
active_tab_background #23372B
active_tab_foreground #C1C497
inactive_tab_background #111c18
inactive_tab_foreground #81B8A8

# Normal colors
color0 #111c18
color1 #FF5345
color2 #549e6a
color3 #459451
color4 #509475
color5 #D2689C
color6 #2DD5B7
color7 #C1C497

# Bright colors
color8 #81B8A8
color9 #FF5345
color10 #549e6a
color11 #459451
color12 #509475
color13 #D2689C
color14 #2DD5B7
color15 #C1C497

# Underline
url_color #509475

# Marks
mark1_foreground #111c18
mark1_background #509475
mark2_foreground #111c18
mark2_background #D2689C
mark3_foreground #111c18
mark3_background #549e6a
