# Solitude - Kitty Terminal Theme

# Background
background #101315

# Foreground
foreground #cacccc

# Cursor
cursor #cacccc
cursor_text_color #101315

# Selection
selection_background #343d41
selection_foreground #cacccc

# Tab bar
active_tab_background #1e2124
active_tab_foreground #cacccc
inactive_tab_background #101315
inactive_tab_foreground #4b4e55

# Normal colors
color0 #101315
color1 #de6145
color2 #9fa5a9
color3 #d9dbdc
color4 #798186
color5 #aeaeae
color6 #707070
color7 #cacccc

# Bright colors
color8 #4b4e55
color9 #de6145
color10 #9fa5a9
color11 #d9dbdc
color12 #798186
color13 #aeaeae
color14 #707070
color15 #cacccc

# Underline
url_color #798186

# Marks
mark1_foreground #101315
mark1_background #798186
mark2_foreground #101315
mark2_background #aeaeae
mark3_foreground #101315
mark3_background #9fa5a9
