source = ~/.cache/quickshell/theme/hyprlock.conf

background {
    monitor =
    path = /home/baizhi/Templates/quick-shell/themes/dracula/wallpaper/wall.png
    blur_passes = 3
    blur_size = 8
}

general {
    hide_cursor = true
}

input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = $accent
    inner_color = $surface
    font_color = $text
    check_color = $warning
    fail_color = $danger

    fade_on_empty = false
    rounding = 14

    placeholder_text = <i>Password...</i>

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M %p")"
    color = $time

    font_size = 90
    font_family = JetBrainsMono Nerd Font Mono

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = $date

    font_size = 18
    font_family = JetBrainsMono Nerd Font Mono

    position = 0, 40
    halign = center
    valign = center
}
