# Horizon - Kitty Terminal Theme

# Background
background #1c1e26

# Foreground
foreground #d5d8da

# Cursor
cursor #e95678
cursor_text_color #1c1e26

# Selection
selection_background #2e303e
selection_foreground #d5d8da

# Tab bar
active_tab_background #16161c
active_tab_foreground #d5d8da
inactive_tab_background #1c1e26
inactive_tab_foreground #6c6f93

# Normal colors
color0 #16161c
color1 #e95678
color2 #29d398
color3 #fab795
color4 #26bbd9
color5 #ee64ac
color6 #59e1e3
color7 #d5d8da

# Bright colors
color8 #6c6f93
color9 #ec6a88
color10 #3fdaa4
color11 #fbc3a7
color12 #3fc4de
color13 #f075b5
color14 #6be4e6
color15 #d5d8da

# Underline
url_color #26bbd9

# Marks
mark1_foreground #1c1e26
mark1_background #e95678
mark2_foreground #1c1e26
mark2_background #b877db
mark3_foreground #1c1e26
mark3_background #29d398
